SCD TYPE 2 (Add New Row – Full History)

CREATE OR REPLACE TABLE CUSTOMER_SCD2 (
    CUSTOMER_SK INT AUTOINCREMENT,   -- Surrogate key
    CUSTOMER_ID INT,
    CUSTOMER_NAME STRING,
    EMAIL STRING,
    START_DATE DATE,
    END_DATE DATE,
    CURRENT_FLAG STRING
);

Insert Initial Record

INSERT INTO CUSTOMER_SCD2
(CUSTOMER_ID, CUSTOMER_NAME, EMAIL, START_DATE, END_DATE, CURRENT_FLAG)
VALUES
(1, 'Alice', 'alice@gmail.com', CURRENT_DATE(), NULL, 'Y');

Change happens (email updated)

UPDATE CUSTOMER_SCD2
SET END_DATE = CURRENT_DATE() - 1,
    CURRENT_FLAG = 'N'
WHERE CUSTOMER_ID = 1
  AND CURRENT_FLAG = 'Y';


  Insert new record

  INSERT INTO CUSTOMER_SCD2
(CUSTOMER_ID, CUSTOMER_NAME, EMAIL, START_DATE, END_DATE, CURRENT_FLAG)
VALUES
(1, 'Alice', 'alice@yahoo.com', CURRENT_DATE(), NULL, 'Y');

Result

SELECT * FROM CUSTOMER_SCD2 ORDER BY CUSTOMER_SK;

