USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE DATABASE ECOMMERCE_DEMO;
USE DATABASE ECOMMERCE_DEMO;
CREATE OR REPLACE SCHEMA REALTIME_PIPELINE;
USE SCHEMA REALTIME_PIPELINE;

USE WAREHOUSE COMPUTE_WH;


CREATE OR REPLACE TABLE ORDERS_RAW (
    ORDER_ID        NUMBER,
    CUSTOMER_ID     NUMBER,
    ORDER_TIME      TIMESTAMP,
    ORDER_STATUS    STRING,
    ORDER_AMOUNT    NUMBER
);


INSERT INTO ORDERS_RAW (ORDER_ID, CUSTOMER_ID, ORDER_TIME, ORDER_STATUS, ORDER_AMOUNT) VALUES
    (1001, 1, CURRENT_TIMESTAMP, 'PLACED', 50),
    (1002, 2, CURRENT_TIMESTAMP, 'PLACED', 75),
    (1003, 3, CURRENT_TIMESTAMP, 'PLACED', 100);

SELECT * FROM ORDERS_RAW;

CREATE OR REPLACE STREAM ORDERS_STREAM
ON TABLE ORDERS_RAW;


INSERT INTO ORDERS_RAW (ORDER_ID, CUSTOMER_ID, ORDER_TIME, ORDER_STATUS, ORDER_AMOUNT) VALUES
    (1004, 4, CURRENT_TIMESTAMP, 'PLACED', 120),
    (1005, 5, CURRENT_TIMESTAMP, 'PLACED', 200);

SELECT * FROM ORDERS_STREAM;

CREATE OR REPLACE TABLE ORDERS_ANALYTICS AS
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_TIME,
    ORDER_STATUS,
    ORDER_AMOUNT
FROM ORDERS_RAW
WHERE 1 = 2;  

SELECT * FROM ORDERS_ANALYTICS;

CREATE OR REPLACE TASK LOAD_ORDERS_TO_ANALYTICS
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('ORDERS_STREAM')
AS
INSERT INTO ORDERS_ANALYTICS (
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_TIME,
    ORDER_STATUS,
    ORDER_AMOUNT
)
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_TIME,
    ORDER_STATUS,
    ORDER_AMOUNT
FROM ORDERS_STREAM;


ALTER TASK LOAD_ORDERS_TO_ANALYTICS RESUME;


INSERT INTO ORDERS_RAW (ORDER_ID, CUSTOMER_ID, ORDER_TIME, ORDER_STATUS, ORDER_AMOUNT) VALUES
    (1006, 6, CURRENT_TIMESTAMP, 'PLACED', 220),
    (1007, 7, CURRENT_TIMESTAMP, 'PLACED', 260);


SELECT * FROM ORDERS_ANALYTICS;


SHOW TASKS LIKE 'LOAD_ORDERS_TO_ANALYTICS';

SELECT
  NAME,
  STATE,
  SCHEDULED_TIME,
  QUERY_START_TIME,
  COMPLETED_TIME,
  ERROR_MESSAGE
FROM TABLE(
  INFORMATION_SCHEMA.TASK_HISTORY(
    TASK_NAME => 'LOAD_ORDERS_TO_ANALYTICS',
    RESULT_LIMIT => 10
  )
);

SELECT *
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY())
WHERE NAME = 'LOAD_ORDERS_TO_ANALYTICS'
ORDER BY COMPLETED_TIME DESC;

SHOW STREAMS;